### ISSUE TITLE
正常使用时报错"SyntaxError: Unexpected eval or arguments in strict mode" 

### ISSUE THREAD

**Issue by dustleafwjl** [huaweicloud/huaweicloud-sdk-nodejs-v3#6]
/Documents/my-workspace/cloud-function/node_modules/@huaweicloud/huaweicloud-sdk-functiongraph/v2/model/FunctionRef.js:5
    function FunctionRef(refName, arguments) {
                                  ^^^^^^^^^

SyntaxError: Unexpected eval or arguments in strict mode
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Documents/my-workspace/cloud-function/node_modules/@huaweicloud/huaweicloud-sdk-functiongraph/v2/public-api.js:77:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by dustleafwjl** [comment]
node版本16.8.0

**Comment by dustleafwjl** [comment]
版本退到3.0.30能跑通

**Comment by mawenbo-huawei** [comment]
收到，下个版本修复问题

**Comment by kejiweixun** [comment]
@akhuang @mawenbo-huawei 这个问题还没修复

**Comment by mawenbo-huawei** [comment]
@akhuang 问题已在`3.0.46-rc`版本修复
